# Generated by Django 2.0 on 2020-03-27 17:31
import swapper
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        swapper.dependency('chaty', 'BaseGroupingEntity')
    ]

    operations = [
        migrations.CreateModel(
            name='BaseGroupingEntity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'swappable': swapper.swappable_setting('chaty', 'BaseGroupingEntity'),
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='created at date')),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='last updated date at')),
                ('content', models.TextField(blank=True, max_length=1000, null=True, verbose_name='content')),
                ('is_read', models.BooleanField(default=False, verbose_name='is_read')),
                ('grouping_entity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='messages', related_query_name='messages', to=swapper.get_model_name('chaty', 'BaseGroupingEntity'), verbose_name='Grouping Entity')),
                ('recipient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='received_messages', related_query_name='received_messages', to=settings.AUTH_USER_MODEL, verbose_name='Recipient')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', related_query_name='sent_messages', to=settings.AUTH_USER_MODEL, verbose_name='Sender')),
            ],
        ),
    ]
